# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: ol-account-api
  azureContainerRegistry: monoprix
  acrUsername: maciej.myszkowski@inetum.world
  acrPassword: Impaq34$

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'ora-sp-sdk/pom.xml'
    goals: 'clean install'
    options: '--settings maven/settings.xml -DskipTests'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    mavenOptions: '-Xmx3072m'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
- task: Maven@3
  inputs:
    mavenPomFile: 'ora-sp-api/pom.xml'
    goals: 'clean install'
    options: '--settings maven/settings.xml -DskipTests'
    publishJUnitResults: false
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
    mavenOptions: '-Xmx3072m'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
- script: |
    echo Construction et tag image docker
    cd $(Build.SourcesDirectory)/ora-sp-api
    docker build -f Dockerfile target -t $(azureContainerRegistry).azurecr.io/$(imageName):latest -t $(azureContainerRegistry).azurecr.io/$(imageName):$(Build.BuildNumber)
    echo Liste des images docker construites
    docker image ls
    echo Connexion Azure Container Registry
    docker login -u $(acrUsername) -p $(acrPassword) $(azureContainerRegistry).azurecr.io
    echo Push image docker vers Azure Container Registry
    docker push $(azureContainerRegistry).azurecr.io/$(imageName):latest
    docker push $(azureContainerRegistry).azurecr.io/$(imageName):$(Build.BuildNumber)
  displayName: 'Construction de l''image docker et push de l''image vers $(azureContainerRegistry)'